### ISSUE TITLE
Introduce support for debain & alpine based distroless images

### ISSUE THREAD

**Issue by Kieran-Muller** [quay/claircore#1018]
## The Problem

[Distroless images](https://github.com/GoogleContainerTools/distroless) somewhat resemble Debian images with their `/etc/os-release` files containing a number of references to detain and the fact that distroless is a slimmed down Debian image.

There are two issues faced with the distroless images currently:
1. The malformed `/etc/os-release` file is causing a bad version string in the dist table so Clair can't match any vulnerabilities correctly
2. Clair is unable to find packages due the non-standard way in which distroless stores them.

### Problem 1 
The malformed `/etc/os-release` file is causing a bad version string in the dist table so Clair can't match any vulnerabilities correctly.

Sample os-release file contents from a distroless based image.
```
$ cat /tmp/static/etc/os-release
PRETTY_NAME="Distroless"
NAME="Debian GNU/Linux"
ID="debian"
VERSION_ID="11"
VERSION="Debian GNU/Linux 11 (bullseye)"
HOME_URL="https://github.com/GoogleContainerTools/distroless"
SUPPORT_URL="https://github.com/GoogleContainerTools/distroless/blob/master/README.md"
BUG_REPORT_URL="https://github.com/GoogleContainerTools/distroless/issues/new"
```

Which leads to an index report as so: 
```json
{
  "manifest_hash": "sha256:f858d0eb854af55df05856e0ef2da291327894d0f01cd3efe2e2cfc6d13e088d",
  "state": "IndexFinished",
  "packages": {},
  "distributions": {
    "5873": {
      "id": "5873",
      "did": "debian",
      "name": "Debian GNU/Linux",
      "version": "11 (Debian GNU/Linux 11 (bullseye)",
      "version_code_name": "Debian GNU/Linux 11 (bullseye",
      "version_id": "11",
      "arch": "",
      "cpe": "",
      "pretty_name": "Debian GNU/Linux 11 (Debian GNU/Linux 11 (bullseye)"
    }
  },
  "repository": {},
  "environments": {},
  "success": true,
  "err": ""
} 
```

As opposed to something more correct:

```json
{
  "manifest_hash": "sha256:182f6734d63194209cf188018f6288480d11d0a7f234f50b60a4db81055cf3c5",
  "state": "IndexFinished",
  "packages": {},
  "distributions": {
    "653": {
      "id": "653",
      "did": "debian",
      "name": "Debian GNU/Linux",
      "version": "11 (bullseye)",
      "version_code_name": "bullseye",
      "version_id": "11",
      "arch": "",
      "cpe": "",
      "pretty_name": "Debian GNU/Linux 11 (bullseye)"
    }
  },
  "repository": {},
  "environments": {},
  "success": true,
  "err": ""
}
```

With the logic seen in [debian/distributionscanner.go](https://github.com/quay/claircore/blob/7d939f415118346e35a851bbe9f97f915d0a99e1/debian/distributionscanner.go#L68)

```
name, nameok := kv[`VERSION_CODENAME`]
idstr := kv[`VERSION_ID`]
if !nameok {
name = strings.TrimFunc(kv[`VERSION`], func(r rune) bool { return !unicode.IsLetter(r) })
}
if name == "" || idstr == "" {
zlog.Info(ctx).
	Err(err).Msg("malformed os-release file")
return nil, nil
}
```
If the release file used contains the correct data, the id 11 and name bullseye will be passed to the [mkDist function](https://github.com/quay/claircore/blob/a2fc410804d55f98bb1a493bafa9b3bdf0e600c9/debian/releases.go#L13C9-L13C9). This would then produce a perfect dist in the db.

However the release file has been tampered with, and if for example `VERSION_CODENAME` is empty/missing, and the `VERSION` field has a value like so: `Debian GNU/Linux 11 (bullseye)`. Then when you run this line`name := strings.TrimFunc("Debian GNU/Linux 11 (bullseye)", func(r rune) bool { return !unicode.IsLetter(r) })` we get `Debian GNU/Linux 11 (bullseye` which is then the value of the name var...

This value, when you go to the `mkDist` function would result in `fmt.Sprintf("Debian GNU/Linux %d (%s)", ver, name)` producing `Debian GNU/Linux 11 (Debian GNU/Linux 11 (bullseye)` with the missing `)` that  would also explain the `version` and `version_code_name` being odd in the DB. 
![cd627000-8797-403c-97c5-5568cce07cb2](https://github.com/quay/claircore/assets/57447348/1548f069-f630-4e0e-bc66-25c4683bc0ae)

#### Potential Solution
Add an additional check to use a regex pattern to verify the `/etc/os-release` `VERSION` field and get the necessary value `/bookworm/bullseye/etc...` etc to be able to assign distroless images as debian similar to the rhel [regex match](https://github.com/quay/claircore/blob/a2fc410804d55f98bb1a493bafa9b3bdf0e600c9/rhel/distributionscanner.go#L84) for `Red Hat Enterprise Linux (?:Server)?\s*(?:release)?\s*(\d+)(?:\.\d)?.` which could be added to the Debian scanners to get the right answer?

### Problem 2 
Clair is unable to find packages due the non-standard way in which distroless stores them.

Distroless stores its package information within the `/var/lib/dpkg` under the `status.d` directory `var/lib/dpkg/status.d`

#### Potential Solution

Introduce an additional method of finding packages for debian that would check the `/var/lib/dpkg/status.d` for package information.

It seems it would require an update to [indexer/layerscanner.go](https://github.com/quay/claircore/blob/main/indexer/layerscanner.go) or related configs. I'm not too familiar with the indexer codebase to determine where in the filesystem information is gathered.

**Comment by Kieran-Muller** [comment]
I have raised a draft PR which aims to tackle Problem 1. Please take a look and let me know your thoughts https://github.com/quay/claircore/pull/1019

**Comment by RTann** [comment]
Problem 2 should be resolved already with https://github.com/quay/claircore/blob/main/dpkg/distroless_scanner.go

**Comment by Kieran-Muller** [comment]
That's brilliant, thanks for pointing that out. 

In that case, is the direction I've taken with the PR the right way to go? 
That being, interpreting distroless as Debian dist?

Would it be more appropriate to go create an entire distroless package with a `distrobutionscannger.go` etc and  add handling to Debian `distrobutionscannger.go` to filter out distroless `os-release` files to prevent them from being added as a Debian item in the dist table?

**Comment by Kieran-Muller** [comment]
Interestingly, I did some investigation into chainguard distroless which is alpine based and because the os-release file matches the pattern of the alpine os-release, no problems arise. Clair is able to generate successful index and vulnerability reports.
