### ISSUE TITLE
Uses Red Hat's Oval v2 instead of v1

### ISSUE THREAD

**Issue by Allda** [quay/claircore#112]
Red Hat recently published v2 stream of Oval data. It covers more than just RHEL product. The format should be the same as v1 with one exception - CPE list contains more accurate data. Clair core should switch to this data source to cover whole Red Hat's portfolio.

https://www.redhat.com/security/data/oval/v2/

https://www.redhat.com/security/data/oval/v2/PULP_MANIFEST should help with identifying which oval files are relevant.

**Comment by ldelossa** [comment]
@Allda 
Currently working on a branch which ensures we correctly parse all our vuln databases for matching. I'll make this work part of that branch.

**Comment by Allda** [comment]
Claircore switched to Oval v2 several weeks ago https://github.com/quay/claircore/pull/196 . Closing this issue now.
