### ISSUE TITLE
[Question] Connection between Clair and ClairCore

### ISSUE THREAD

**Issue by MVrachev** [quay/claircore#117]
Hi, I am familiar with [Clair](https://github.com/quay/clair) and I am wondering **_what is the connection between Clair and ClairCore?_**

Is this a library that will be used in Clair in the future?

**Comment by ldelossa** [comment]
Hello @MVrachev 

ClairCore will be the backing "engine" for ClairV4. 
ClairV4 will be integrated with Quay.io over the next month. 
Once integration is finalized the master branch of Clair will link to ClairCore.

**Comment by ldelossa** [comment]
@MVrachev closing this, open back up if you have more questions.
