### ISSUE TITLE
Vulnerability Severity Should be an Enum

### ISSUE THREAD

**Issue by alecmerdler** [quay/claircore#119]
### Description

In previous Clair implementation, the `Severity` of a given `Vulnerability` would be one of a defined enum. Currently, [this struct field is typed as `string`](https://github.com/quay/claircore/blob/master/vulnerability.go#L17). We can make this a static type.

**Comment by ldelossa** [comment]
@alecmerdler 

We discussed this when designing ClairCore. We decided to not create a heuristic around differing severity strings for the vulnerability databases we parse. This leads us to make narrow assumptions on potentially many different severity strings.

Im am open for debate on this however. Maybe @hdonnay has some thoughts. 


For now, Severity will be a direct mapping of the value provided by the vulnerability database being parsed.

**Comment by alecmerdler** [comment]
@ldelossa Clients of `claircore` will absolutely need some sort of guarantee on what values to expect. See the [values we currently use in Quay](https://github.com/quay/quay/blob/master/util/secscan/__init__.py). It is understandable that arbitrary mappings between different databases will make assumptions, but without it, how are clients able to filter, sort, and map across vulnerabilities?

**Comment by ldelossa** [comment]
okay @alecmerdler 

@josephschorr @hdonnay and I discussed this. We will add a "NormalizedSeverity" field to the vulnerability model (naming can be debated here). This will be where Clair, and other tools implementing the ClairAPI will specify the currently in use enum list.

Id like to do this in all one PR and this will take some digging to find how the sec db's we parse display their severity and create a mapping in our parser.

Stay tuned.
