### ISSUE TITLE
IndexReport State Should be an Enum

### ISSUE THREAD

**Issue by alecmerdler** [quay/claircore#124]
### Description

Clients will rely on the `IndexReport.State` field, which is [currently typed as `string`](https://github.com/quay/claircore/blob/master/indexreport.go#L23). The documentation claims that the Indexer follows a [finite state machine with defined states](https://quay.github.io/claircore/v0.0.14/indexer_architecture.html). We can use these as a typed Go string enum.

**Comment by hdonnay** [comment]
This will be fixed via the Clair API, if at all.
