### ISSUE TITLE
Add support for modular rpm

### ISSUE THREAD

**Issue by Allda** [quay/claircore#128]
Modular rpms are a special type of rpms which require different vulnerability detection.

Modular rpms are stored in the rpm database and can be distinguished from normal rpms by `RPMTAG_MODULARITYLABEL` label.

Clair v3 already has a modular rpm detection: https://github.com/quay/clair/pull/891

In oval vulnerability data, modular rpms can be also distinguished by looking at criterion comments.

`<criterion test_ref="oval:com.redhat.rhsa:tst:20190980027" comment="Module httpd:2.4 is enabled"/>`

**Comment by ldelossa** [comment]
@Allda would you have the time to work this into ClairCore?

**Comment by Allda** [comment]
This feature has been already implemented in the following PRs.
https://github.com/quay/claircore/pull/156 https://github.com/quay/claircore/pull/148
