### ISSUE TITLE
Add a means to force re-indexing of a manifest.

### ISSUE THREAD

**Issue by hdonnay** [quay/claircore#132]
This would be incredibly useful when developing new scanners. As is, we unconditionally cache results, which is certainly the correct choice in a "real" environment.

**Comment by mcoops** [comment]
@hdonnay what were we thinking here?

My initial thought would be an optional argument on starting the indexer to force the re-indexing. 

Or would it make more sense to somehow add an optional parameter in the API when calling the indexer?

**Comment by hdonnay** [comment]
I was thinking it'd be an additional parameter to `Libindex.Index` that could then be wired into the HTTP API via a query parameter. And maybe a switch to disallow it via the Libindex options struct.

**Comment by hdonnay** [comment]
Closed via #521
