### ISSUE TITLE
Scanning of layers fails for some of the docker image .

### ISSUE THREAD

**Issue by 16bce091** [quay/claircore#141]
Whenever we try to generate report using the cctool , It gives an error of i/o timeout for some of the layers.But after 3-4 days it works fine listing all the vulnerabilities of an image. Can anyone tell why this is happening??

These are the attached screenshots for your reference.

![image_manifest](https://user-images.githubusercontent.com/50020569/76387573-435e1800-638d-11ea-9fc7-d391713ba09a.png)
![logs_report](https://user-images.githubusercontent.com/50020569/76387578-4527db80-638d-11ea-8b65-ecb102c41781.png)

**Comment by ldelossa** [comment]
@16bce091 

Can you confirm, at the time CCTOOL i/o timesout, the layers can be retrieved by a computer on the same network you are running cctool? 

I.E can you isolate this to just a CCTOOL issue and not a general network issue. From those logs it looks like a general network issue
