### ISSUE TITLE
Ubuntu Precise and Artful urls 404

### ISSUE THREAD

**Issue by ldelossa** [quay/claircore#157]
```
7:47PM WRN updater error error="updater ubuntu-precise-updater failed to update: failed to parse the fetched vulnerability database: failed to decode OVAL xml contents: expected element type <oval_definitions> but have <html>" component=libvuln/New
7:47PM WRN updater error error="updater ubuntu-artful-updater failed to update: failed to parse the fetched vulnerability database: failed to decode OVAL xml contents: expected element type <oval_definitions> but have <html>" 
```

@alexmurray did ubuntu stop hosting these oval sec dbs? The root site no longer has directory listing and ClairCore is failing to retrieve these.

**Comment by alexmurray** [comment]
Yes, precise and artful are both very much end of life and are not supported. We only maintain and publish OVAL for the supported releases. See https://wiki.ubuntu.com/Releases for more details.

**Comment by ldelossa** [comment]
@alexmurray that was my hunch, but thanks for confirming. Ill remove them from our code base.

**Comment by ldelossa** [comment]
@alexmurray is there an API endpoint which tracks supported ubuntu releases? I know there is a website for user facing, but anything we can parse ?

**Comment by alexmurray** [comment]
@ldelossa You could use the launchpad API for this - see https://lists.ubuntu.com/archives/ubuntu-release/2019-April/004757.html
