### ISSUE TITLE
INT package and distribution ID may not be large enough

### ISSUE THREAD

**Issue by ldelossa** [quay/claircore#17]
Currently package and distribution structs use INT for their ID. These IDs uniquely identify the given resource. There's some concern about the number of unique packages overflowing an int's space. 

Solutions:
Use UUID in postgres as the primary key. pgcrypto extensions is necessary
Generate unique name derived from fields on the entity such as "name"
Big serial can be used as the primary key in the database

I am leaning toward UUID in the database. @hdonnay @jzelinskie curious about opinions.

**Comment by hdonnay** [comment]
Moved to bigserials with #100.
