### ISSUE TITLE
CentOS Support

### ISSUE THREAD

**Issue by ldelossa** [quay/claircore#184]
When inventorying issues in Clair I discovered a CentOS vulnerability source PR introduced by @irenexychen 
https://github.com/quay/clair/pull/761

Looks like CentOS has a security database called CESA. I was unaware of this. We should begin investigating CentOS support and this security database.

**Comment by SofyaTavrovskaya** [comment]
Hi, guys!
Do you plan to add support of Centos-based images?

Clairv4 returns empty report when scanning centos-based image. 

```
stavrovskaya@stavrovskaya-pc:~/clair/cmd/clairctl$ ./clairctl report centos:centos7
centos:centos7 ok
```

Clairv2 finds following vulnerabilities:

```
centos:centos7 bind-license (32:9.11.4-26.P2.el7) RHSA-2020:5011 Medium   32:9.11.4-26.P2.el7_9.2 
               curl (7.29.0-59.el7)               RHSA-2020:5002 Medium   0:7.29.0-59.el7_9.1     
               libcurl (7.29.0-59.el7)            RHSA-2020:5002 Medium   0:7.29.0-59.el7_9.1     
               python (2.7.5-89.el7)              RHSA-2020:5009 Medium   0:2.7.5-90.el7          
               python-libs (2.7.5-89.el7)         RHSA-2020:5009 Medium   0:2.7.5-90.el7 
```

It seems like Clairv4 can't detect distribution in image and matching vulnerabilities with packages

**Comment by ldelossa** [comment]
This looks feasible for Clair V4. We will need to prioritize this effort. 

This is also open for community contribution.

**Comment by aciddude** [comment]
> Hi, guys!
> Do you plan to add support of Centos-based images?
> 
> Clairv4 returns empty report when scanning centos-based image.
> 
> ```
> stavrovskaya@stavrovskaya-pc:~/clair/cmd/clairctl$ ./clairctl report centos:centos7
> centos:centos7 ok
> ```
> 
> Clairv2 finds following vulnerabilities:
> 
> ```
> centos:centos7 bind-license (32:9.11.4-26.P2.el7) RHSA-2020:5011 Medium   32:9.11.4-26.P2.el7_9.2 
>                curl (7.29.0-59.el7)               RHSA-2020:5002 Medium   0:7.29.0-59.el7_9.1     
>                libcurl (7.29.0-59.el7)            RHSA-2020:5002 Medium   0:7.29.0-59.el7_9.1     
>                python (2.7.5-89.el7)              RHSA-2020:5009 Medium   0:2.7.5-90.el7          
>                python-libs (2.7.5-89.el7)         RHSA-2020:5009 Medium   0:2.7.5-90.el7 
> ```
> 
> It seems like Clairv4 can't detect distribution in image and matching vulnerabilities with packages

This bug was fixed in this pull  https://github.com/quay/claircore/pull/261

and mentioned here: https://github.com/quay/clair/issues/1114

We need to wait for a new claircore version to be released or you can build everything yourself :-)

**Comment by ldelossa** [comment]
@aciddude I do not believe that ticket you are referring to adds CentOS support. 

we would need a CentOS distribution scanner implemented, along with a centOS vulnerability database.

**Comment by SofyaTavrovskaya** [comment]
@ldelossa, thank you for response

@aciddude I scanned image  centos:centos7 with the last changes in claircore, which including and this bug fixes  #261 too. 
If you choose as output format for report - JSON, you will see finding packages in image:

```"packages":{"140":{"id":"140","name":"centos-release","version":"7-9.2009.0.el7.centos","kind":"binary","source":{"id":"139","name":"centos-release","version":"7-9.2009.0.el7.centos","kind":"source","normalized_version":"","cpe":""},"normalized_version":"","arch":"x86_64","cpe":""},"142":{"id":"142","name":"filesystem","version":"3.2-25.el7","kind":"binary","source":{"id":"141","name":"filesystem","version":"3.2-25.el7","kind":"source","normalized_version":"","cpe":""},"normalized_version":"","arch":"x86_64","cpe":""},"144":{"id":"144","name":"basesystem","version":"10.0-7.el7.centos","kind":"binary","source":{"id":"143","name":"basesystem","version":"10.0-7.el7.centos","kind":"source","normalized_version":"","cpe":""},"normalized_version":"","arch":"noarch","cpe":""},"146":{"id":"146","name":"tzdata","version":"2020d-2.el7","kind":"binary","source":{"id":"145","name":"tzdata","version":"2020d-2.el7","kind":"source","normalized_version":"","cpe":""},"normalized_version":"","arch":"noarch","cpe":""},"148":{"id":"148","name":"glibc-common","version":"2.17-317.el7","kind":"binary","source":{"id":"147","name":"glibc","version":"2.17-317.el7","kind":"source","normalized_version":"","cpe":""},"normalized_version":"","arch":"x86_64","cpe":""},"150":{"id":"150","name":"nspr","version":"4.25.0-2.el7_9","kind":"binary","source":{"id":"149","name":"nspr","version":"4.25.0-2.el7_9","kind":"source","normalized_version":"","cpe":""},"normalized_version":"","arch":"x86_64","cpe":""}```

But you won't see distribution in report, it's empty value:
`"distributions":{}`
because distribution scanner hasn't implemented yet.

**Comment by ldelossa** [comment]
@SofyaTavrovskaya 

It will be difficult to add support to CentoOS without an official security database.

**Comment by SofyaTavrovskaya** [comment]
Is it possible to use RHEL database for it?

**Comment by aciddude** [comment]
> @aciddude I do not believe that ticket you are referring to adds CentOS support.
> 
> we would need a CentOS distribution scanner implemented, along with a centOS vulnerability database.

Well In general doesn't the RHEL database cover CentOS ?  

I was just trying to help point out why CentOS shows as "OK" for v4 but not v2

**Comment by ldelossa** [comment]
As of today, we so not have CentOS distribution identification, nor do we have a mechanism to cross map CentOS packages to RHEL advisories. 

A direct mapping from CentOS to RHEL advisories may not be accurate. 

@Allda has done the most work with mapping RHEL images to RHEL advisories, and currently this uses RHEL specific CPE mappings. (Lmk if you have any input here Ales). 

I can do some research on mapping CentOS dists. and packages to RHEL advisories, my initial concern is that a naive mapping may produce incorrect results.

**Comment by ldelossa** [comment]
As of today, we will not support CentOS. 

See: https://groups.google.com/g/clair-dev/c/4ZnoxPn3iSE 
and https://issues.redhat.com/browse/PROJQUAY-1793?filter=12360089
