### ISSUE TITLE
Linux coalescer doesn't remove obsolete packages

### ISSUE THREAD

**Issue by Allda** [quay/claircore#213]
Linux coalescer includes packages that are no present in the final container image into the index report. This happens when a package is installed in a layer and later either updated, downgraded or removed in other layers. Current coalescer implementation keeps both (original and updated) in index report even though original package is no longer in an image.

Here is an example of such a index report with updated package.
```json
{
  "packages": {
    "4040": {
      "id": "4040",
      "name": "vim-minimal",
      "version": "2:7.4.160-3.el7",
      "kind": "binary",
      "source": {
        "id": "4039",
        "name": "vim",
        "version": "7.4.160-3.el7",
        "kind": "source",
        "normalized_version": "",
        "cpe": ""
      },
      "normalized_version": "",
      "arch": "x86_64",
      "cpe": ""
    },

    "4324": {
      "id": "4324",
      "name": "vim-minimal",
      "version": "2:7.4.160-4.el7",
      "kind": "binary",
      "source": {
        "id": "4323",
        "name": "vim",
        "version": "7.4.160-4.el7",
        "kind": "source",
        "normalized_version": "",
        "cpe": ""
      },
      "normalized_version": "",
      "arch": "x86_64",
      "cpe": ""
    }
  }
}
```

The package `vim-minimal-2:7.4.160-3.el7` is not present in final image because it was replaced by `vim-minimal-2:7.4.160-4.el7`

**Comment by mcoops** [comment]
Will help our here, looking into it.

**Comment by ldelossa** [comment]
@Allda and @mcoops the Coalescer was changed by Ales sometime after v0.0.25. You will notice the code is different 
https://github.com/quay/claircore/blob/v0.0.25/internal/indexer/linux/coalescer.go

vs

https://github.com/quay/claircore/blob/master/internal/indexer/linux/coalescer.go

can you guys first confirm this behavior present in v0.0.25? If it is not, the changes to the coalescer is causing this issue. 

If they are we need to troubleshoot further.

**Comment by ldelossa** [comment]
@Allda @mcoops can you please try out the following branch: 

https://github.com/quay/claircore/tree/louis/coalescer-fix

I reworked the coalescer utilizing some new data structures. Let me know if this fixes the issue.
