### ISSUE TITLE
Add a Go modules scanner, and updater

### ISSUE THREAD

**Issue by jasinner** [quay/claircore#216]
For Go binaries built with [go modules](https://github.com/golang/go/wiki/Modules#additional-resources), GA in Go 1.14, it's possible to extract the module information from the binary using '[goversion -m](https://pkg.go.dev/rsc.io/goversion?tab=doc)'.

I'm not sure there is a currently a reliable source for vulnerabilities Golang libraries for an updater, perhaps from Github, like [NextB's vulnerability scanner is doing](https://github.com/nexB/vulnerablecode/blob/develop/vulnerabilities/importers/github.py)?

**Comment by ldelossa** [comment]
@jasinner just a ping on this, we are definitely interested. We are finishing up our GA release and our introduction into http://github.com/quay/quay 

Once this finishes up right around mid November, we will have more time to look deeper into this. Sorry about delay.

**Comment by ldelossa** [comment]
Let's track this work in #127

Going to link and and close this issue, refer to 127 moving forward.
