### ISSUE TITLE
Support vulnerability listing for maven central repo artifacts

### ISSUE THREAD

**Issue by arajkumar** [quay/claircore#236]
Maven is a package repository for Java. 

The `mvn` tool which packs the maven projects usually adds metadata fields(dependency name, version) into `META-INF/maven/<groupId>/<artifactId>` which could be found on every `jar` file.

There are two files with in every maven jar which would give us the necessary information like `package|version`,
- META-INF/maven/<groupId>/<artifactId>/pom.properties
- META-INF/maven/<groupId>/<artifactId>/pom.xml

> The pom.xml and pom.properties files are packaged up in the JAR so that each artifact produced by Maven is self-describing and also allows you to utilize the metadata in your own application if the need arises. One simple use might be to retrieve the version of your application. Operating on the POM file would require you to use some Maven utilities but the properties can be utilized using the standard Java API and look like the following:

```
#Generated by Maven
#Tue Oct 04 15:43:21 GMT-05:00 2005
version=1.0-SNAPSHOT
groupId=com.mycompany.app
artifactId=my-app
```

Reference: https://maven.apache.org/guides/getting-started/#how-do-i-add-resources-to-my-jar

**Comment by arajkumar** [comment]
I would be happy to contribute if there are no concerns on this ask. @ldelossa @hdonnay

**Comment by ldelossa** [comment]
@arajkumar does maven provide its own security db? If so can you link us to it? 

This seems like a fine thing to do. 

You will need to write a package scanner which finds and peeks into .jar files. IIRC jar is just a zip formatted archive so that seems fine. 

Writing a parser for the xml items would be necessary.

**Comment by arajkumar** [comment]
> @arajkumar does maven provide its own security db? If so can you link us to it?
As now my plan to use CRDA remote matcher for maven, similar to what we are trying for Python #203.

But in the long run we have to plug it with NVD(CPE as matching criteria) for non CRDA use cases.,(similar to https://github.com/jeremylong/DependencyCheck).

**Comment by ldelossa** [comment]
Okay, just keep in mind that we are unable to support client notifications unless we index the database of vulnerabilities. Any CRDA provided results will not provide notifications to clients when contents has changed (since we cannot detect the change)

**Comment by arajkumar** [comment]
Trivy is using Github Advisory as a data source: https://github.com/advisories?query=ecosystem%3Amaven

Gitlab also has public security advisory database for maven: https://gitlab.com/gitlab-org/security-products/gemnasium-db/-/tree/master/maven
