### ISSUE TITLE
updater: failed to parse alpine-main-v3.6 and alpine-community-v3.3 JSON vulnerability databases

### ISSUE THREAD

**Issue by SofyaTavrovskaya** [quay/claircore#294]
Alpine-updater fails when trying parse alpine-main-v3.6 and alpine-community-v3.3 JSON vulnerability database.

Clair-matcher logs:
`ERR encountered error while updating error="updating errors:\n\talpine-main-v3.6-updater: failed to parse the fetched vulnerability database: json: cannot unmarshal object into Go struct field Details.packages.pkg.secfixes of type []string\n\talpine-community-v3.3-updater: failed to parse the fetched vulnerability database: json: cannot unmarshal object into Go struct field SecurityDB.packages of type []alpine.Package\n" component=libvuln/New`

    
Clair version/image: clairV4.0.
Claircore: v0.1.20

**Comment by ldelossa** [comment]
This is a known issue with Alpine. Please track this issue here: https://github.com/quay/clair/issues/1155#issuecomment-756387328

We are waiting for Alpine to fix this.

**Comment by SofyaTavrovskaya** [comment]
@ldelossa Thanks!
