### ISSUE TITLE
There is now way to limit number of indexer's DB connections

### ISSUE THREAD

**Issue by jan-zmeskal** [quay/claircore#308]
So I recently deployed clair from [this commit](https://github.com/quay/clair/commit/eb519e0752d3cf7f5f8daeefd4ad9bd29cbfa8c2) to quite a big environment. The reason why I mention the commit is that before the deployment, I did not have @hdonnay 's postgres refactor deployed. I don't know if that's significant information, but I think it might given [these changes](https://github.com/quay/claircore/pull/266/files#diff-a7d7db14845dc0c99ee7c38e117721015b9406ad32a63544ade17750142b0834). What happened is that indexer pods used up way more DB connections than I expected. Details of the issue are described in my message to @ldelossa.
![image](https://user-images.githubusercontent.com/22600243/107488618-e617ab80-6b87-11eb-8917-08e016ff407a.png)

I read the code for a bit since then and as far as I can understand, there's no real way to ultimately limit the overall number of how many DB connections one indexer instance creates. Keep in mind that my understanding might be wrong, but let me walk you through it. 

First the easy part. One connection pool is created during [store initialization](https://github.com/quay/claircore/blob/533316c18965c9007f1fb60bead2f33cf012d715/libindex/init.go#L25). The number of max connections is hard-coded to 30. As described in quay/clair/issues/1179, it'd be nice to have some control over that. But that's not the main problem because we could just scale down the number of indexer pods to deal with that. I think the catch is in different place.

When a POST request is made to `index_report` endpoint, [Index](https://github.com/quay/claircore/blob/533316c18965c9007f1fb60bead2f33cf012d715/libindex/libindex.go#L91) method of `Libindex` is eventually called. That in turn makes call to [controllerFactory](https://github.com/quay/claircore/blob/533316c18965c9007f1fb60bead2f33cf012d715/libindex/controllerfactory.go#L20) function. And each call to that function creates a new connection pool with options acquired from connstring. If an option is not specified in connstring, it falls back to some sane defaults chosen by library authors. For [number of maximum connections](https://github.com/jackc/pgx/blob/3568b908c03beaf0846015658ca9fd3123c51823/pgxpool/pool.go#L15), it's 4. Furthermore, value of `defaultMaxConnIdleTime` is 30 minutes. With all this being said, I think it's apparent now that when there's a lot of index requests, one might run out of DB connections.

Now please correct me if I'm wrong in my analysis. But if not, I think we need a mechanism how to limit the overall number of DB connections indexer may make.

**Comment by ldelossa** [comment]
@jan-zmeskal the auxillary pools you are referencing here: https://github.com/quay/claircore/blob/533316c18965c9007f1fb60bead2f33cf012d715/libindex/controllerfactory.go#L20 

are used only for our distlock implementation. https://github.com/quay/claircore/tree/master/pkg/distlock

We have a new implementation. I believe we can set a limit on that pool so that it does not create more then 1 connection per lock. Will need to double check this.

We also have this in the works: https://github.com/ldelossa/distlock 
In the new distlock implementation we guarantee on a single long-held database connection will be used for ALL locks during a process's lifetime. This should be going into Clair in the next few weeks.

**Comment by jan-zmeskal** [comment]
That sounds like something that might help us greatly. As of now, my clair instance keeps hitting max number of DB connections because indexer ate eats up almost all of them. I don't know what kind of effect will this have on matcher's and notifier's abilities long term, so the sooner we have this, the better. If I have some new findings, I'll post them here.

**Comment by ldelossa** [comment]
Are you able to test setting the pool's max connection to 1 or 2 in the controllerFactory you linked above? You can add some items to the "cfg" returned by the pgx api call: https://github.com/quay/claircore/blob/533316c18965c9007f1fb60bead2f33cf012d715/libindex/controllerfactory.go#L22

If this fixes the issue, open a PR from your fork.

**Comment by jan-zmeskal** [comment]
I actually had a similar idea. I wanted to let it just run for a couple of hours as it is to see if the number of connections starts dropping, but it doesn't seems so as long as index requests are coming. So yeah, later today I'll changing the code in my fort and deploy from my fork.

**Comment by jan-zmeskal** [comment]
I deployed indexer with these settings:
```
indexer:
  connstring: host=<censored> port=5432 dbname=<censored> user=<censored> password=<censored> sslmode=disable application_name=clair-indexer pool_max_conns=1 pool_max_conn_idle_time=5m0s
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: False
```
and it seems to have helped, at least for now. I'll monitor it for couple more hours and will let you know.

**Comment by ldelossa** [comment]
@jan-zmeskal cool, if that works and doesn't cause errors of any sort, open a PR that just sets it in the config. This will be a workaround until we get the new distlock implementation in.

**Comment by jan-zmeskal** [comment]
If no issue occurs, we can keep the workaround on the configuration level until we have the fix. At least that seems like a better idea to me. I think it makes sense not to put temporary workarounds in code if it can be avoided.

**Comment by ldelossa** [comment]
@jan-zmeskal no, hard coding the conn pool is a fine solution, its an error that we didn't do this originally.

**Comment by ldelossa** [comment]
This pull adds setting the maxconns in notifier: https://github.com/quay/clair/pull/1236

**Comment by hdonnay** [comment]
This is fixed properly with connection strings, now.
