### ISSUE TITLE
runtime.NumCPU possibly unreliable in containers

### ISSUE THREAD

**Issue by hdonnay** [quay/claircore#397]
I think that `runtime.NumCPU()` will report the number of cores on the machine (ala `nproc(1)`) which doesn't represent the number of cores actually available. If this is the case, some of our queue sizing will be too large when containerized.

**Comment by crozzy** [comment]
@hdonnay can this be closed now?

**Comment by hdonnay** [comment]
Yeah. We'll still need to make changes in clair so that GOMAXPROCS is set automatically.
