### ISSUE TITLE
GC: CPU intensive workload

### ISSUE THREAD

**Issue by crozzy** [quay/claircore#516]
Running the GC can cause high resource utilization on the DB, particularly CPU consumption. After consulting with @kwestpharedhat he suggested some low hanging improvements that could be implemented (and some not so low hanging).

- [x] Rewrite `SELECT id FROM vuln WHERE vuln.updater = $1 AND id > $2 ORDER BY id ASC LIMIT 10000;` to `SELECT id FROM vuln WHERE vuln.updater = $1 AND id > $2 and id < $2 + 1000;` as the ORDER BY is a heavy CPU consumer.
- [ ] Create an index on `vuln` like so `create index vuln_update_id on vuln (id, updater);`
- [ ] Rework the batch query mechanism submit a few large queries rather than many small ones that could DDOS the query planner.

https://github.com/quay/claircore/blob/main/internal/vulnstore/postgres/gc.go#L202-L210 can be replaced with:

```
delete from vuln using vuln as v
left join uo_vuln uvl
    on v.id = uvl.vuln
where uvl.vuln is null
and v.updater = $1
and v.id > $2 and v.id < $2 + 1000
```

cc/ @hdonnay @kwestpharedhat

**Comment by hdonnay** [comment]
SGTM

I think the many-small-queries is an antipattern in postrges

**Comment by crozzy** [comment]
https://github.com/quay/claircore/pull/517/files this was taken care of here
