### ISSUE TITLE
Clair indexing/reporting timeout in offline mode.

### ISSUE THREAD

**Issue by bluefriday** [quay/claircore#525]
When I use clair openAPI to do 'indexing' and 'reporing' operations, clair will see the address(https://access.redhat.com/security/data/metrics/repository-to-cpe.json\) associated with redhat.

```
4:41AM INF index request start component=libindex/Libindex.Index manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108
4:41AM DBG configured search API URL api=https://search.maven.org/solrsearch/select component=java/Scanner.Configure manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108 version=3
4:41AM DBG attempting fetch of repo2cpe mapping file component=rhel/repo2cpe/UpdatingMapper.do manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108 url=https://access.redhat.com/security/data/metrics/repository-to-cpe.json version=1.1


4:41AM ERR configuration failed error="Get \"https://access.redhat.com/security/data/metrics/repository-to-cpe.json\": dial tcp 23.25.172.12:443: i/o timeout" component=internal/indexer/layerscannner/New manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108 scanner=rhel-repository-scanner
4:41AM DBG locking attempt component=libindex/Libindex.Index manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108
4:41AM DBG locking OK component=libindex/Libindex.Index manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108
4:41AM INF starting scan component=internal/indexer/controller/Controller.Index manifest=sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108
```

I found that If both values of Repo2CPEMappingURL and Repo2CPEMappingFile are empty, the path of access.redhat specified as DefaultRepo2CPEMappingURL 
- https://github.com/quay/claircore/blob/84ab16a9e05cec84226be3216f25d43f004fa7d4/rhel/repositoryscanner.go#L113

Of course, even if this operation fails after a 30 second timeout, because of the 'fallthrough' statement inside the switch statement, the operation continues and eventually indexing and reporting succeed.

I want to perform indexing and reporting without timeout for online access. What should I do in this case?

**Comment by hdonnay** [comment]
There's a config option you can set to specify a local file. This has to be handled separately because of an oddity of how offline support is implemented (this will be fixed in the future, but it does require some rocket surgery).

The [Red Hat Quay documentation](https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html/manage_red_hat_quay/clair-intro2#mapping_repositories_to_common_product_enumeration_cpe_information) has some notes on how to configure things.
