### ISSUE TITLE
alpine 3.7 parser error

### ISSUE THREAD

**Issue by ldelossa** [quay/claircore#56]
libvuln reports a parsing error for alpine 3.4 

```
ERR error from updater: updater alpine-main-v3.4-updater failed to update: failed to parse the fetched vulnerability database: yaml: unmarshal errors:
  line 37: mapping key "2.4.27-r1" already defined at line 27 component=libvuln
```

fix to sec db has been opened:
https://github.com/alpinelinux/alpine-secdb/pull/5

Waiting for comments or merger

**Comment by mor1** [comment]
Thanks -- as alpine-secdb is autogenerated from the APKBUILD files in `aports`, it would be better to just regenerate. (And, having checked locally, doing so appears to remove this duplication.) I'll try and get that done.

**Comment by ldelossa** [comment]
Issue is resolved: 
`3:57PM INF successfully updated the vulnstore component=update-controller interval=30m0s name=alpine-main-v3.4-updater`

Thanks @mor1

**Comment by ldelossa** [comment]
@mor1 

Hey there, it looks like we are experiencing this issue again with alpine 3.7 security database.

```
alpine-main-v3.7-updater: failed to parse the fetched vulnerability database: yaml: unmarshal errors:\n  line 707: mapping key \"1.8.3-r1\" already defined at line 705\'
```

would you be able to assist once again?

**Comment by ldelossa** [comment]
@mor1 This issue is resolved by utilizing the json definitions instead of yaml.
