### ISSUE TITLE
error from debian dynamic distributions

### ISSUE THREAD

**Issue by paulaldridge** [quay/claircore#873]
Upgraded to a clair version with dynamic distributions for debian (from v4.4.4 to v.4.6.0) and seeing the following error:

```
failed constructing factory, excluding from run
debian: unable to do OVAL HEAD request: Head "https://www.debian.org/security/oval/oval-definitions-etch.xml":  read tcp REDACTED->REDACTED: read: connection reset by peer
```

How I'm reading the [code](https://github.com/quay/claircore/blob/main/debian/updater.go#L143) it does seem like getting the distros from http://archive.debian.org/debian/dists/ and then using them to build urls to https://www.debian.org/security/oval/ will hit these problems, as there is only a subset of those distros available. Should these be allowed errors, i.e. [expecting some updaters to not populate](https://github.com/quay/claircore/blob/main/debian/updater.go#L158), or is there something I'm missing? 

Thanks!

**Comment by hdonnay** [comment]
That just 404's on my machine:
```
% curl -IL https://www.debian.org/security/oval/oval-definitions-etch.xml                                                                                         🖳
HTTP/2 404 
content-location: 404.en.html
vary: negotiate,accept-language,cookie
tcn: choice
x-content-type-options: nosniff
x-frame-options: sameorigin
referrer-policy: no-referrer
x-xss-protection: 1
permissions-policy: interest-cohort=()
strict-transport-security: max-age=15552000
last-modified: Wed, 01 Mar 2023 19:47:26 GMT
etag: "20e2-5f5dbfb52795d;5f5e70ba257d0;5f71703ca374
accept-ranges: bytes
content-length: 8418
x-clacks-overhead: GNU Terry Pratchett
content-type: text/html
content-language: en
date: Fri, 17 Mar 2023 15:10:26 GMT
server: Apache
```

**Comment by paulaldridge** [comment]
Thanks Hank, yep I see what you mean. Agreed that url doesn't exist so will always return 404. Problem is that the code returns on line [158](https://github.com/quay/claircore/blob/main/debian/updater.go#L158) before getting to the switch, which excludes the whole debian factory rather than just skipping the failing debian version.

**Comment by hdonnay** [comment]
Yeah, but my point is that an error there is some sort of network or HTTP protocol error. Being unable to contact the server at all means it's unlikely to succeed if it keeps chugging along.

**Comment by paulaldridge** [comment]
Ah ok I see what you mean sorry! I though the 404 was being treated as an error rather than falling through to the switch, but you are right it will fall through. Must be something blocking the connection our end, thanks for looking at this
