### ISSUE TITLE
Support for Amazon Linux 2023

### ISSUE THREAD

**Issue by purplexed** [quay/claircore#968]
Hello,

Currently the clair project only supports Amazon Linux AMI 2018.03 and Amazon Linux 2 from the AWS images. Since Clair is used for the basic security scanning on ECR, are there any plans to support Amazon Linux 2023?

Thanks!

**Comment by crozzy** [comment]
Hi!

There are no plans yet but it could be added fairly trivially. Part of the work should be to try and make it the distributions dynamic so that these issues don't come up in the future (see  ubuntu, debian, alpine etc etc)

**Comment by stewartsmith** [comment]
My attempt at that trivial adding (revision 2): https://github.com/quay/claircore/pull/990

**Comment by hdonnay** [comment]
Seems done
