### ISSUE TITLE
Support for Debian 12 Bookworm

### ISSUE THREAD

**Issue by cageyv** [quay/claircore#977]
There is an error from AWS ECR scanner:
```
UnsupportedImageError: The operating system 'debian' version '12' is not supported.
```

Probably this happens because Bookwork was released at 2023-06-10 and claircore was released at 2023-06-09 :(

**Comment by cageyv** [comment]
Apologies for the interruption, @crozzy, but I wanted to bring your attention to that issue

**Comment by crozzy** [comment]
Testing with `main` and debian:bookworm we get:
```json
  "distributions": {
    "2": {
      "id": "2",
      "did": "debian",
      "name": "Debian GNU/Linux",
      "version": "12 (bookworm)",
      "version_code_name": "bookworm",
      "version_id": "12",
      "arch": "",
      "cpe": "",
      "pretty_name": "Debian GNU/Linux 12 (bookworm)"
    }
  },
```
The error you reported is from ECR, we have no way to know what version of Clair/Claircore ECR is running or how Clair is configured so it's difficult to debug what's happening without that information. The debian distribution discovery has been dynamic for a while now (i.e we shouldn't need to hardcode any new distributions into claircore), all that to say; we don't know what in Clair would trigger an `UnsupportedImageError`.

**Comment by cageyv** [comment]
Okay, well. I guess next release will solve that issue automatically, because of dynamic distribution discovery
