### ISSUE TITLE
[Resolved] Debian Oval feed phasing out uncompressed Oval files 

### ISSUE THREAD

**Issue by Kieran-Muller** [quay/claircore#978]
I reached out to Debian security through `team@security.debian.org & security@debian.org` to ask if there was an issue with their [oval feed ](https://www.debian.org/security/oval/) as the `https://www.debian.org/security/oval/oval-definitions-bookworm.xml` file seemed to be missing/broken, producing a binary result when downloaded as opposed to the xml files the other Oval files produce. 

The response was as follows: 
> We're slowly phasing out uncompressed OVAL files, please use:
> https://www.debian.org/security/oval/oval-definitions-bookworm.xml.bz2
> which makes it clearer as to what format you're getting.

They are transition to using bzip2 compressed files instead. I am trying to get information on the timeline for this change.

We're using claircore v1.4.17 which seems is incompatible with this change as this version is built to handle .xml files only and not compressed files. https://github.com/quay/claircore/blob/v1.4.17/debian/updater.go#L147

If it's the case that later versions of clair are retrieving debian vulnerability data through other means and not running in to issues, or are compatible with the Oval feed changes it would be great to know. Thanks

**Comment by Kieran-Muller** [comment]
I have followed up with the Debian security team, there is no timeline in place for the removal on uncompressed .xml files from the Oval feeds and no announcement has been made as of yet.

**Comment by crozzy** [comment]
Hi, thanks for reporting the issue.

Recently we updated the debian updater to use the security-tracker information (https://github.com/quay/claircore/pull/888). So this behaviour should be mitigated in newer versions of claircore. Those updaters are also configurable so you _could_ potentially override the bookworm OVAL URL but unless you have some access to the uncompressed data (or you have some process uncompressing and serving the data) then I don't suppose that'd be much use.
