### ISSUE TITLE
osv: duplicated ecosystems

### ISSUE THREAD

**Issue by hdonnay** [quay/claircore#992]
I noticed that the OSV updater reports duplicated ecosystems:
```
ecosystems=["almalinux","almalinux","almalinux","gsd","go","hex","maven","nuget","packagist","pub","pypi","rocky linux","rocky linux","rocky linux","rubygems","uvi","crates.io","npm"]
```

This has the smell of a loop variable bug.

**Comment by crozzy** [comment]
It appear like the different versioned ecosytems will produce the duplicates i.e. (AlmaLinux, AlmaLinux:8, AlmaLinux:9) When `driver.UpdaterSet.Add()` is called it will return an error if an updater with the same name has already been registered. Looks like we're disregarding that error.
